### PR TITLE
add TON Gram Faucet

### PR DESCRIPTION
**Pull request by AlexBSoft**

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks for addition!
by link Got error:

```Error code: SSL_ERROR_INTERNAL_ERROR_ALERT```

DO you know what cause this issue?

**Comment by AlexBSoft** [comment]
This issue was caused by Heroku SSL. It is fixed now.

**Comment by skywinder** [comment]
Thanks! is it your project?

**Comment by AlexBSoft** [comment]
Yes it is

**Review by H-saeedi — APPROVED** [review]

**Pull request merged**
